title: Sameer Afzal
logo: headshot_circle.png
description: Data Scientist with a Master’s in Data Science and 4+ years of experience in data science, software engineering, and machine learning. Proficient in Python, R, and SQL to build predictive models and generate actionable insights. Skilled in Power BI, Tableau, Databricks, BigQuery, and Azure for scalable, data-driven solutions. Strong background in data engineering, including ETL, cleaning, and feature engineering, with experience in agile project delivery.
theme: jekyll-theme-minimal
